# Generated by Django 4.2.5 on 2023-11-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_medico', '0002_alter_antecedentes_alergias_alter_antecedentes_otros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='dado_de_alta',
            field=models.BooleanField(blank=True, default=False, verbose_name='Paciente dado de alta'),
            preserve_default=False,
        ),
    ]
