# Generated by Django 4.2.5 on 2023-11-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_medico', '0003_evaluacion_dado_de_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentes',
            name='respiratorio',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='tiempo_enfermedad',
            field=models.CharField(max_length=30),
        ),
    ]
