# Generated by Django 4.2.5 on 2023-11-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_medico', '0004_antecedentes_respiratorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenfisico',
            name='actitud_postural',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='actividades_motoras',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='coordinacion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Equilibrio y coordinación'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='grado_funcional',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='orientacion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Orientación'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='reflejos',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
