# Generated by Django 4.2.5 on 2023-11-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_medico', '0005_alter_examenfisico_actitud_postural_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dolorinfo',
            name='grado_de_enfermedad',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dolorinfo',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona de dolor'),
        ),
        migrations.AlterField(
            model_name='dolorinfo',
            name='distribucion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Distribución del dolor'),
        ),
        migrations.AlterField(
            model_name='dolorinfo',
            name='nivel',
            field=models.IntegerField(verbose_name='Grado de dolor'),
        ),
        migrations.AlterField(
            model_name='dolorinfo',
            name='ocurrencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dolorinfo',
            name='palpacion',
            field=models.BooleanField(verbose_name='Dolor a la palpitación'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='actividades_motoras',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Actividades motrices'),
        ),
    ]
