# Generated by Django 4.2.5 on 2023-11-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_medico', '0007_alter_dolorinfo_nivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacioncorporal',
            old_name='tipo_sensibilidad',
            new_name='sensibilidad_profunda',
        ),
        migrations.RemoveField(
            model_name='evaluacioncorporal',
            name='rango_articular',
        ),
        migrations.RemoveField(
            model_name='evaluacioncorporal',
            name='sensibilidad',
        ),
        migrations.AddField(
            model_name='evaluacioncorporal',
            name='rangos_articulares',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='evaluacioncorporal',
            name='sensibilidad_superficial',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacioncorporal',
            name='tono_muscular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
