# Generated by Django 4.2.5 on 2023-11-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_medico', '0008_rename_tipo_sensibilidad_evaluacioncorporal_sensibilidad_profunda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacioncorporal',
            name='nivel_fuerza',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
