# Generated by Django 4.2.5 on 2023-11-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_medico', '0009_alter_evaluacioncorporal_nivel_fuerza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacion',
            old_name='observaciones',
            new_name='consideraciones',
        ),
        migrations.RenameField(
            model_name='evaluacion',
            old_name='plan_tratamiento',
            new_name='plan_de_tratamiento',
        ),
        migrations.RenameField(
            model_name='observaciones',
            old_name='control_esfinter',
            new_name='control_esfinteres',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='enfermedad',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='enfermedad_actual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='observaciones_y_consideraciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observaciones',
            name='ayuda_diagnosticada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='observaciones',
            name='estado_de_animo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='observaciones',
            name='pruebas_especiales',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='observaciones',
            name='sentidos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
