# Generated by Django 4.2.5 on 2023-11-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_medico', '0010_rename_observaciones_evaluacion_consideraciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
