# Generated by Django 4.2.5 on 2023-11-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_medico', '0011_evaluacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='plan_de_tratamiento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
