# Generated by Django 4.2.5 on 2023-11-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_medico', '0012_alter_evaluacion_plan_de_tratamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='medicamentos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
