# Generated by Django 4.2.5 on 2023-11-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_medico', '0014_antecedentes_cardiaco_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentes',
            name='cardiaco_tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Antecedentes Cardiacos'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='diabetes_tipo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='hta_tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='HTA'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='operaciones_tipo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Operaciones'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='respiratorio_tipo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Antecedentes Respiratorios'),
        ),
    ]
