# Generated by Django 4.2.5 on 2023-11-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_de_citas', '0003_rename_estado_terapista_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(default='S', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terapista',
            name='estado_civil',
            field=models.CharField(default='S', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='terapista',
            name='telefono',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
