# Generated by Django 4.2.5 on 2023-11-02 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historial_medico', '0014_antecedentes_cardiaco_tipo_and_more'),
        ('administracion_de_citas', '0004_paciente_estado_civil_terapista_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial_medico.evaluacion'),
        ),
    ]
